'use client'
import { Inter } from "next/font/google";
import React from 'react';
import { Button, Layout, Menu, theme } from 'antd';
import { Link } from 'next';
import "./globals.css";

const { Header, Content, Footer } = Layout;

const items = new Array(2).fill(null).map((_, index) => ({
  key: index + 1,
  label: `nav ${index + 1}`,
}));

// const navLink = {
//   key : 1,
//   label

// }
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <html>
        <body>
          <Layout>
          <Header style={{ position: 'fixed', padding: '0 0 0 0', width: '100%', zIndex: 100, display: 'flex', alignItems: 'center', background: 'transparent' }}>
              <div float='right' />
              <Menu
                theme="light"
                mode="horizontal"
                defaultSelectedKeys={['2']}
                items={items}
                style={{ flex: 1, minWidth: 10 }}
                className="transparent-menu"
              />
            </Header>
            <Content >
              <div
                style={{
                  background: colorBgContainer,
                  position: 'fixed',
                  minHeight: 800,
                  padding: '4% 0 0 0',
                  borderRadius: borderRadiusLG,
                  width: '100%'
                }}
              >
                <div style={{ width: '50%', alignItems: 'center'}}>
                  {children}
                </div>
              </div>
            </Content>
        </Layout>
      </body>
    </html>
  );
};
