'use client'
import { Inter } from "next/font/google";
import React from 'react';
import { Breadcrumb, Layout, Menu, theme } from 'antd';
import "./globals.css";

const { Header, Content, Footer } = Layout;

const items = new Array(2).fill(null).map((_, index) => ({
  key: index + 1,
  label: `nav ${index + 1}`,
}));

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <html>
        <body>
          <Layout>
            <Header style={{ display: 'stretch', alignItems: 'center' }} className="transparent-menu">
              <div float='right' />
              <Menu
                theme="light"
                mode="horizontal"
                defaultSelectedKeys={['2']}
                items={items}
                style={{ flex: 0, minWidth: 1000 }}
                className="transparent-menu"
              />
            </Header>
            <Content style={{ padding: '0 4px' }} >
              <div
                style={{
                  background: colorBgContainer,
                  minHeight: 748,
                  padding: 0,
                  borderRadius: borderRadiusLG,
                }}
              >
                {children}
              </div>
            </Content>
        </Layout>
      </body>
    </html>
  );
};
